version: '3.1'
services:
  mongo:
    image: mongo:latest
    container_name: m06-uf3-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db


  mongo-express:
    image: mongo-express:latest
    container_name: m06-uf3-mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: "mongodb://root:password@m06-uf3-mongo:27017/"
volumes:
  mongo-data: